Update nalgebra to fix compilation error on Rust 1.40
In Rust 1.40 a future-compatibility-warning will become a hard error, which will cause the dependency `nalgebra v0.17.2` to no longer compile.

```
rust-sloth$ cargo +nightly check
    Checking nalgebra v0.17.2
error[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
   --> /home/myname/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.17.2/src/base/cg.rs:297:44
    |
297 |                 self[(j, i)] += shift[j] * self[(D::dim() - 1, i)];
    |                 ---------------------------^^^^-------------------
    |                 |                          |
    |                 |                          immutable borrow occurs here
    |                 mutable borrow occurs here
    |                 mutable borrow later used here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0502`.
error: could not compile `nalgebra`.

To learn more, run the command again with --verbose.
```

To fix this, I ran `cargo update --package nalgebra` to update it to `v0.17.3`.

(Btw, just `cargo update` causes the terminal renderer to mess up...)